<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tasks extends Model
{
    use HasFactory;

    public const STATUS_NEW = '0';
    public const STATUS_DONE = '1';


    protected $fillable = [
      'name',
    ];


    public static  function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model){
            $model->done = 0;
        });
    }

    public static function getStatusLabel(int $status)
    {
        $statusMap = [
            0 => 'Новое',
            1 => 'Выполнено',

        ];
        foreach ($statusMap as $statusId => $statusName) {
            if ($status === $statusId) {
                return $statusName;
            }
        }
    }
}
